default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  username: root
  ppassword:

development:
  <<: *default
  database: sokudokubunko_development

test:
  <<: *default
  database: sokudokubunko_test

production:
  <<: *default
  username: root
  database: sokudokubunko_production
  password: <%= ENV['SOKUDOKU-BUNKO_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: sokudoku-bunko_development
# test:
#   <<: *default
#   database: sokudoku-bunko_test
# production:
#   <<: *default
#   database: sokudoku-bunko_production
#   username: sokudoku-bunko
#   password: <%= ENV['SOKUDOKU-BUNKO_DATABASE_PASSWORD'] %>
