default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sokudokubunko_development

test:
  <<: *default
  database: sokudokubunko_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: sokudoku-bunko_development
# test:
#   <<: *default
#   database: sokudoku-bunko_test
# production:
#   <<: *default
#   database: sokudoku-bunko_production
#   username: sokudoku-bunko
#   password: <%= ENV['SOKUDOKU-BUNKO_DATABASE_PASSWORD'] %>
